config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :users
  end

  get 'admin/index'

  resources :employers, :uniform_piece_groups, :uniform_piece_kinds
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  get 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  
  post 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'
  get 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'

  resources :uniform_pieces

   root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :employer
  
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  before_save { self.email = email.downcase }
  validates :employer, :role, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, length: { minimum: 6 }, allow_blank: true, on: :update
  validates :email,    presence: true, format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }

  def admin?
    self.role == 'admin'
  end

  def default?
    self.role == 'default'
  end
end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :require_user
  before_action :require_admin, only: [:index, :new, :create, :destroy]
  before_action :is_logged_user?, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :employer_id, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :employer, label: 'Dados do funcionário:', disabled: !current_user.admin? %>
    <%= f.input :role, label: 'Regra:',
                          as: :select,
                          default: 'default',
                          collection: [['Padrão', 'default'], ['Administrador', 'admin']],
                          disabled: !current_user.admin? %>
    <%= f.input :email, label: 'E-mail:' %>
    <%= f.input :password, label: 'Senha:' %>
    <%= f.input :password_confirmation, label: 'Repita a senha:' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: 'Salvar', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar dados do usuário</h1>

<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Detalhes', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<div class="row">
  <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-8">
    <h1>Listing Users</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th>Regra</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.employer.avatar, size: '25x25' %>
            <td><%= link_to user.employer.name, user %>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><%= link_to 'Editar', edit_user_path(user) %></td>
            <!-- td><%= link_to 'Remover', user, method: :delete, data: { confirm: 'Você têm certeza?' } %></td -->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Novo Usuário', new_user_path %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Novo usuário</h1>

<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= link_to @user.employer.name, employer_path(@user.employer.id) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Regra:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>