config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :users
  end

  get 'admin/index'

  resources :employers, :uniform_piece_groups, :uniform_piece_kinds
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  get 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  
  post 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'
  get 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'

  resources :uniform_pieces

   root 'home#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :uniform_pieces
  
  before_save { self.name = name.humanize.titleize }
  
  before_save { self.avatar = 'https://c1.staticflickr.com/9/8542/8666789945_0077a6d060.jpg' }
  
  validates :name, :admission, :sex, presence: true
  
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :require_user
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.order(:name)
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
    @uniform_pieces = UniformPiece.where(employer_id: nil, gender: [@employer.sex, 'U'])
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Novo funcionário criado com sucesso.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Funcionário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Funcionário excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :avatar, :sex, :admission, :dismiss)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= simple_form_for(@employer, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nome completo' %>
    <%= f.input :avatar, label: 'Foto' %>
    <%= f.input :sex, label: 'Sexo',
                      as: :select,
                      default: 'M',
                      selected: @employer.sex,
                      collection: [['Masculino', 'M'], ['Feminino', 'F']] %>
    <div class='datetimerange'>
      <%= f.input :admission, label: 'Admissão:', as: :date_picker, input_html: {data: {date_options: {defaultDate: Date.current }}}%>
      <%= if !f.object.new_record?
            f.input :dismiss, label: 'Demissão:', as: :date_picker, input_html: {data: {date_options: {defaultDate: '' }}}
      end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Salvar", class: "btn-primary btn-block" %>
  </div>
<% end %>

app/views/employers/_uniforms.html.erb
<hr>
<h1>Uniformes</h1>
<hr>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Adicionar peça de uniforme</button>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Adicionar peças ao funcionário</h4>
      </div>
      <div class="modal-body">
        <table id="pieces"
                 data-toggle="table"
                 data-page-size="5"
                 data-page-list="[5,10,20,40,80,100]"
                 data-pagination="true"
                 data-id-field="id"
                 data-click-to-select="true"
                 data-maintain-selected="true"
                 data-pagination-first-text="Primieiro"
                 data-pagination-pre-text="Anterior"
                 data-pagination-next-text="Próximo"
                 data-pagination-last-text="Último"
                 data-checkbox-header="false"
                 data-filter-control="true">
          <thead>
            <tr>
              <th data-field="state"    data-checkbox="true"></th>
              <th data-field="id"       data-sortable="true">#</th>
              <th data-field="kind"     data-sortable="true" data-filter-control="select">Tipo</th>
              <th data-field="group"    data-sortable="true" data-filter-control="select">Grupo</th>
              <th data-field="gender"   data-sortable="true" data-filter-control="select">Gênero</th>
              <th data-field="size"     data-sortable="true" data-filter-control="select">Tamanho</th>
              <th data-field="color"    data-sortable="true" data-filter-control="select">Cor</th>
              <th data-field="used"     data-sortable="true" data-filter-control="select">Usado</th>
            </tr>
          </thead>
          <tbody>
            <% @uniform_pieces.each do |uniform_piece| %>
              <tr>
                <td></td>
                <td><%= uniform_piece.id %></td>
                <td><%= uniform_piece.uniform_piece_kind.name %></td>
                <td><%= uniform_piece.uniform_piece_group.name %></td>
                <td><%= gender(uniform_piece.gender) %></td>
                <td><%= uniform_piece.uniform_piece_size.name %></td>
                <td><%= uniform_piece.color %></td>
                <td><%= "Usado" unless !uniform_piece.used? %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <hr>
        <%= simple_form_for :pieces, url: uniform_pieces_to_employer_path, method: :post do |f| %>
          <table id="piecesToEmployer"
                  data-toggle="table"
                  data-id-field="id"
                  data-unique-id="id"
                  data-checkbox-header="false"
                  data-select-item-name="pieces[]">
            <thead>
              <tr>
                <th data-checkbox="true"  data-field="state"></th>
                <th data-field="id"       data-sortable="true">#</th>
                <th data-field="kind"     data-sortable="true" data-filter-control="select">Tipo</th>
                <th data-field="group"    data-sortable="true" data-filter-control="select">Grupo</th>
                <th data-field="gender"   data-sortable="true" data-filter-control="select">Gênero</th>
                <th data-field="size"     data-sortable="true" data-filter-control="select">Tamanho</th>
                <th data-field="color"    data-sortable="true" data-filter-control="select">Cor</th>
                <th data-field="used"     data-sortable="true" data-filter-control="select">Usado</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
          <input name="employer" value="<%= @employer.id %>" type="hidden">
          <%= f.submit 'Salvar', class: "btn btn-default", id: "btnSalvar" %>

        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Controle</th>
      <th>Grupo</th>
      <th>Tipo</th>
      <th>Tamanho</th>
      <th>Cor</th>
      <th>Data para troca</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @employer.uniform_pieces.each do |uniform_piece| %>
      <tr>
        <td>#<%= uniform_piece.id.to_s.rjust(5,'0') %></td>
        <td><%= link_to uniform_piece.uniform_piece_group.name, uniform_piece %></td>
        <td><%= uniform_piece.uniform_piece_kind.name %></td>
        <td><%= uniform_piece.uniform_piece_size.name %></td>
        <td><%= uniform_piece.color %></td>
        <td><%= ((uniform_piece.entry + 1.year) - Date.today).to_i %> dias</td>
        <td>
          <%= link_to 'Remover', uniform_pieces_return_to_stock_path(up: uniform_piece.id), remote: true %>
        </td>
        <td><%= link_to 'Editar', edit_uniform_piece_path(uniform_piece) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/employers/edit.html.erb
<h1>Editar funcionário</h1>

<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Detalhes', @employer %> |
<%= link_to 'Voltar', employers_path %>

app/views/employers/index.html.erb
<div class="row">
  <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-8">

    <h1>Funcionários</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>Nome</th>
          <th>Sexo</th>
          <th>Data de admissão:</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @employers.each do |employer| %>
          <tr>
            <td><%= image_tag employer.avatar, size: '30x30', class: 'img-circle'%></td>
            <td><%= link_to employer.name, employer %>
            <td><%= (employer.sex == 'M') ? 'Masculino' : 'Feminino' %></td>
            <td><%= employer.admission.strftime("%d/%m/%Y") %></td>
            <td><%= link_to 'Editar', edit_employer_path(employer) %></td>
            <!-- td><%= link_to 'Remover', employer, method: :delete, data: { confirm: 'Você têm certeza?' } %></td -->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Novo funcionário', new_employer_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/employers/new.html.erb
<h1>Novo funcionário</h1>

<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<hr>
<h1>Dados do funcionário</h1>
<hr>
<div class="row">
  <div class="col-md-12 column">
    <div class="col-md-6 column text-right">
      <table class="table table-hover">
        <tr>
          <th>Nome:</th>
          <th><%= @employer.name %></th>
        </tr>
        <tr>
          <th>Sexo:</th>
          <th><%= (@employer.sex == 'M') ? 'Masculino' : 'Feminino' %></th>
        </tr>
        <tr>
          <th>Data de admissão:</th>
          <th><%= @employer.admission.strftime("%d/%m/%Y") %></th>
        </tr>
        <tr>
          <th><%= "Data de demissão:" unless !@employer.dismiss %></th>
          <th><%= @employer.dismiss ? @employer.dismiss.strftime("%d/%m/%Y") : "Usuário ativo" %></th>
        </tr>
      </table>
      <%= link_to 'Editar', edit_employer_path(@employer), class: "btn btn-default" %>
      <%= link_to 'Voltar', employers_path, class: "btn btn-default" %>
    </div>
    <div class="col-md-6 column">
      <p>
        <% if @employer.avatar %>
          <%= image_tag @employer.avatar, width: 200 %>
        <% else %>
          <%= image_tag 'large_avatar.png' %>
        <% end %>
      </p>
    </div>
    <div class="col-md-12 column">
      <%= render "uniforms" %>
    </div>
  </div>
</div>