config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :users
  end

  get 'admin/index'

  resources :employers, :uniform_piece_groups, :uniform_piece_kinds
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  get 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  
  post 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'
  get 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'

  resources :uniform_pieces

   root 'home#index'

end

app/models/uniform_piece.rb
class UniformPiece < ActiveRecord::Base
  belongs_to :uniform_piece_kind
  belongs_to :uniform_piece_group
  belongs_to :uniform_piece_size
  belongs_to :employer

  attr_accessor :amount

  validates :amount, :entry, :uniform_piece_kind, :uniform_piece_group, :uniform_piece_size, :gender, :color, presence: true
end

app/controllers/uniform_pieces_controller.rb
class UniformPiecesController < ApplicationController
  before_action :require_user
  before_action :set_uniform_piece, only: [:show, :edit, :update, :destroy]

  # GET /uniform_pieces
  # GET /uniform_pieces.json
  def index
    @uniform_pieces = UniformPiece.all
  end

  # GET /uniform_pieces/1
  # GET /uniform_pieces/1.json
  def show
  end

  # GET /uniform_pieces/new
  def new
    @uniform_piece = UniformPiece.new
  end

  # GET /uniform_pieces/1/edit
  def edit
  end

  def is_free?(pieces)
    pieces.each do |piece|
      if !piece.employer_id.nil?
        return false
      else
        return true
      end
    end
  end

  def to_employer
    @employer = Employer.find(params[:employer])
    pieces = UniformPiece.find(params[:pieces])

    if is_free?(pieces)
      pieces.each do |piece|
        piece.amount = 0
        piece.delivered = Date.today
        piece.employer = @employer
        piece.save
      end
    else

    end

    @uniform_pieces = UniformPiece.where(id: params[:pieces])

  end

  def return_to_stock

  end
  def employee_return
    @uniform_piece = UniformPiece.find(params[:id])
    employer = @uniform_piece.employer

    @uniform_piece.assign_attributes(employer_id: nil, returned: Date.today)

    respond_to do |format|
      if @uniform_piece.save(validate: false)
        format.html { redirect_to employer_path(employer), notice: 'Uniforme devolvido para o estoque com sucesso.' }
      else
        format.html { redirect_to employer_path, notice: 'Ocorreu um erro ao devolver uniforme para o estoque.' }
      end
    end
  end


  # POST /uniform_pieces
  # POST /uniform_pieces.json
  def create
    saved = false
    @uniform_piece = UniformPiece.new(uniform_piece_params)

    1.upto(@uniform_piece.amount.to_i) do
      if @uniform_piece.save
        @uniform_piece = UniformPiece.new(uniform_piece_params)
        saved = true
      end
    end

    if saved == true
      redirect_to uniform_pieces_path, notice: 'Peças de uniforme criadas com sucesso.'
    else
      render :edit
    end
  end

  # PATCH/PUT /uniform_pieces/1
  # PATCH/PUT /uniform_pieces/1.json
  def update
    user = @uniform_piece.employer
    respond_to do |format|
      if @uniform_piece.update(uniform_piece_params)
        if @uniform_piece.employer_id.nil?
          format.html { redirect_to user, notice: 'Uniform piece was successfully updated.' }
        else
          format.html { redirect_to @uniform_piece, notice: 'Uniform piece was successfully updated.' }
          format.json { render :show, status: :ok, location: @uniform_piece }
        end
      else
        format.html { render :edit }
        format.json { render json: @uniform_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uniform_pieces/1
  # DELETE /uniform_pieces/1.json
  def destroy
    @uniform_piece.destroy
    respond_to do |format|
      format.html { redirect_to uniform_pieces_url, notice: 'Uniform piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uniform_piece
      @uniform_piece = UniformPiece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uniform_piece_params
      params.require(:uniform_piece).permit(:amount, :entry, :delivered, :delivery_reason, :returned, :return_reason, :uniform_piece_size_id, :color, :uniform_piece_kind_id, :uniform_piece_group_id, :gender, :used, :employer_id)
    end
end

app/helpers/uniform_pieces_helper.rb
module UniformPiecesHelper
  def gender(gender)
    case gender
      when 'M'
        'Masculino'
      when 'F'
        'Feminino'
      when 'U'
        'Unisex'
    end
  end
end

app/views/uniform_pieces/_form.html.erb
<div class="form-inputs">
  <label>Controle:</label>
  <input type="text" class="form-control" value="#<%= @uniform_piece.id.to_s.rjust(4, '0') %>" disabled>
</div>

<%= simple_form_for(@uniform_piece) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= if f.object.new_record?
          f.input :amount, label: 'Quantidade de entrada:',
                           as: :integer, input_html: { min: '1', step: 'any', value: 1 }
        else
          f.input :amount, as: :hidden, input_html: { value: 0 }
        end %>
    <div class='datetimerange'>
      <%= f.input :entry, label: 'Data de entrada no estoque:', as: :date_picker, input_html: {data: {date_options: {defaultDate: Date.current }}} %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.association :uniform_piece_kind, label: ("Tipo de peça: (#{link_to 'Criar novo tipo', new_uniform_piece_kind_path, remote: true})").html_safe %>
      </div>
      <div class="col-md-6">
        <%= f.association :uniform_piece_group, label: ("Grupo: (#{link_to 'Criar novo grupo', new_uniform_piece_group_path, remote: true})").html_safe %>
      </div>
    </div>
    <div class='datetimerange'>
      <%= if !f.object.new_record?
            f.input :delivered, label: 'Data de entrega ao funcionário:', as: :date_picker
      end %>
    </div>
    <%= if !f.object.new_record?
          f.input :delivery_reason, label: 'Obs. sobre entrega da peça ao funcionário:'
        end %>
    <div class='datetimerange'>
      <%= if !f.object.new_record?
            f.input :returned, label: 'Data de devolução:', as: :date_picker
      end %>
    </div>
    <%= if !f.object.new_record?
          f.input :return_reason, label: 'Obs. sobre devolução da peça pelo funcionário:'
        end %>
    <div class="row">
      <div class="col-md-6">
        <%= f.association :uniform_piece_size, label: 'Tamanho da peça:',
                                                as: :select,
                                                prompt: 'Tamanho',
                                                selected: @uniform_piece.uniform_piece_size_id %>
      </div>
      <div class="col-md-6">
        <%= f.input :gender, label: 'Gênero:',
                              prompt: 'Gênero',
                              as: :select,
                              collection: [['Masculino', 'M'],['Feminino','F'],['Unisex','U']] %>
      </div>
    </div>
    <%= f.input :color, label: "Cor:" %>
     <!-- if !f.object.new_record? -->
          <%= f.input :used, label: 'Peça usada' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: 'Salvar', class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/uniform_pieces/_return_to_stock.html.erb
<div class="form-inputs">
  <label>Controle:</label>
  <input type="text" class="form-control" value="#<%= @uniform_piece.id.to_s.rjust(4, '0') %>" disabled>
</div>

<%= simple_form_for(@uniform_piece) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :employer_id, as: :hidden, input_html: { value: '' } %>
    <%= f.input :used, as: :hidden, input_html: { value: true } %>
    <%= f.input :amount, as: :hidden,
                         label: 'Quantidade de entrada:',
                         input_html: { min: '1', step: 'any', value: 1 } %>
  </div>
  <div class='datetimerange'>
    <%= f.input :returned, label: 'Data de devolução:', as: :date_picker, input_html: { value: date_br(Date.today) }, required: true %>
  </div>
  <%= f.input :return_reason, label: 'Obs. sobre devolução da peça pelo funcionário:', required: true %>

  <div class="form-actions">
    <%= f.button :submit, value: 'Remover', id: "submit_piece", class: "btn btn-primary btn-block", required: true %>
  </div>
<% end %>

app/views/uniform_pieces/edit.html.erb
<h1>Editando peça de uniforme</h1>
<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>
<div class="row">
  <div class="col-md-12 column">
    <%= link_to 'Detalhes', @uniform_piece %> |
    <%= link_to 'Voltar', uniform_pieces_path %>
  </div>
</div>

app/views/uniform_pieces/index.html.erb
<h1>Uniformes</h1>

<div class="row">
  <div class="col-md-12 column">
    <div class="row">
      <div class="col-md-12 column">
        <%= link_to 'Nova peça de uniforme', new_uniform_piece_path, class: "btn btn-primary" %>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 column">
    		<div class="panel-group" id="panel-163973">
          <% UniformPieceGroup.all.each_with_index do |uniformGroup, i| %>
      			<div class="panel panel-default">
      				<div class="panel-heading">
      					 <a class="panel-title" data-toggle="collapse" data-parent="#panel-163973" href="#collapse-<%= i %>"><%= uniformGroup.name %></a>
      				</div>
      				<div id="collapse-<%= i %>" class="panel-collapse collapse">
      					<div class="panel-body">
                  <% UniformPieceKind.all.each do |uniform_piece_kind| %>
                    <div class="col-md-3">
                      <div class="thumbnail">
                        <div class="caption">
                          <h4 class="text-center">
                            <%= uniform_piece_kind.name %> - <%= UniformPiece.where(uniform_piece_kind_id: uniform_piece_kind.id, uniform_piece_group_id: uniformGroup.id, employer: nil).count(:uniform_piece_kind_id) %>
                            <hr>
                            <% UniformPiece.select(:uniform_piece_size_id).where(uniform_piece_kind_id: uniform_piece_kind.id, uniform_piece_group_id: uniformGroup.id).distinct.each do |piece_size| %>
                              <%= piece_size.uniform_piece_size.name %> - <%= UniformPiece.where(uniform_piece_kind_id: uniform_piece_kind.id, uniform_piece_group_id: uniformGroup.id, uniform_piece_size_id: piece_size.uniform_piece_size.id, employer: nil ).count(:uniform_piece_size_id) %><br>
                            <% end %>
                          </h4>
                        </div>
                      </div>
                    </div>
                  <% end %>
      					</div>
      				</div>
      			</div>
          <% end %>
          <div class="panel panel-default">
    				<div class="panel-heading">
    					 <a class="panel-title" data-toggle="collapse" data-parent="#panel-163973" href="#collapse-todos">Todos</a>
    				</div>
    				<div id="collapse-todos" class="panel-collapse collapse">
    					<div class="panel-body">
                <div class="col-md-12">

                  <table id="table"
                         data-toggle="table"
                         data-show-toggle="true"
                         data-show-columns="true"
                         data-pagination="true"
                         data-page-size="10"
                         data-page-list="[5,10,20,40,80,100]"
                         data-pagination-first-text="Primieiro"
                         data-pagination-pre-text="Anterior"
                         data-pagination-next-text="Próximo"
                         data-pagination-last-text="Último"
                         data-filter-control="true">
                    <thead>
                      <tr>
                        <th data-filed="id"         data-sortable="true">#</th>
                        <th data-field="kind"       data-sortable="true" data-filter-control="select">Tipo</th>
                        <th data-field="group"      data-sortable="true" data-filter-control="select">Grupo</th>
                        <th data-field="gender"     data-sortable="true" data-filter-control="select">Gênero</th>
                        <th data-field="size"       data-sortable="true" data-filter-control="select">Tamanho</th>
                        <th data-field="color"      data-sortable="true" data-filter-control="select">Cor</th>
                        <th data-field="used"       data-sortable="true">Usado</th>
                        <th data-field="employer"   data-sortable="true" data-filter-control="select">Funcionário</th>
                        <th data-field="entry"      data-sortable="true" data-filter-control="input">Entrada no estoque</th>
                        <th data-field="delivered"  data-sortable="true" data-filter-control="input">Entregue ao funcionário</th>
                        <th data-field="returned"   data-sortable="true" data-filter-control="input">Devolução p/ estoque</th>
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @uniform_pieces.order(:id).each do |uniform_piece| %>
                        <tr>
                          <td><%= link_to uniform_piece.id.to_s.rjust(4, '0'), uniform_piece_path(uniform_piece) %></td>
                          <td><%= uniform_piece.uniform_piece_kind.name %></td>
                          <td><%= uniform_piece.uniform_piece_group.name %></td>
                          <td><%= gender(uniform_piece.gender) %></td>
                          <td><%= uniform_piece.uniform_piece_size.name %></td>
                          <td><%= uniform_piece.color %></td>
                          <td><%= "Usado" unless !uniform_piece.used? %></td>
                          <td><%= link_to(uniform_piece.employer.name.split(" ")[0], employer_path(uniform_piece.employer)) if !uniform_piece.employer.nil? %></td>
                          <td><%= uniform_piece.entry.strftime("%d/%m/%Y") %></td>
                          <td><%= uniform_piece.delivered.strftime("%d/%m/%Y") if !uniform_piece.delivered.nil? %></td>
                          <td><%= uniform_piece.returned.strftime("%d/%m/%Y") if !uniform_piece.returned.nil? %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
  </div>
</div>

app/views/uniform_pieces/new.html.erb
<h1>Nova peça de uniforme</h1>
<div class="row">
  <div class="col-md-6 column">
    <%= render 'form' %>
  </div>
</div>
<div class="row">
  <div class="col-md-12 column">
    <%= link_to 'Voltar', uniform_pieces_path %>
  </div>
</div>

app/views/uniform_pieces/return_to_stock.html.erb
hello

app/views/uniform_pieces/return_to_stock.js.erb
$('.modal-title').html('Devolver peça');
$('.modal-body').html('<% @uniform_piece = UniformPiece.find(params[:up]) %>');
$('.modal-body').html('<%= escape_javascript(render partial: "return_to_stock") %>');
$('.modal-footer').remove();
$("#myModal").modal('show');

app/views/uniform_pieces/show.html.erb
<h1>Dados da peça de uniforme</h1>

<p>
  <strong>Controle:</strong>
  #<%= @uniform_piece.id.to_s.rjust(4, '0') %>
</p>

<p>
  <strong>Data de entrada:</strong>
  <%= @uniform_piece.entry %>
</p>

<p>
  <strong>Data de entrega ao funcionário:</strong>
  <%= @uniform_piece.delivered %>
</p>

<p>
  <strong>Obs. sobre entregada peça ao funcionário:</strong>
  <%= @uniform_piece.delivery_reason %>
</p>

<p>
  <strong>Data de devolução da peça pelo funcionário:</strong>
  <%= @uniform_piece.returned %>
</p>

<p>
  <strong>Obs. sobre a devolução da peça:</strong>
  <%= @uniform_piece.return_reason %>
</p>

<p>
  <strong>Tamanho da peça:</strong>
  <%= @uniform_piece.uniform_piece_size.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @uniform_piece.color %>
</p>

<p>
  <strong>Uniform piece kind:</strong>
  <%= @uniform_piece.uniform_piece_kind.name %>
</p>

<p>
  <strong>Uniform piece group:</strong>
  <%= @uniform_piece.uniform_piece_group.name %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @uniform_piece.gender ? 'Masculino' : 'Feminino' %>
</p>

<p>
  <strong>Usado:</strong>
  <%= @uniform_piece.used %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @uniform_piece.employer.name unless @uniform_piece.employer.nil? %>
</p>

<%= link_to 'Editar', edit_uniform_piece_path(@uniform_piece) %> |
<%= link_to 'Voltar', uniform_pieces_path %> |
<%= link_to 'Remover', @uniform_piece, method: :delete, data: { confirm: 'Você têm certeza?' } %>

app/views/uniform_pieces/to_employer.html.erb
<div class="row">
  <div class="col col-md-12">
    <%= link_to("Imprimir", "#", onclick: "PrintDiv();", class: 'btn btn-default') %>
    <hr>

    <div id="receiptToPrint">
      <%= image_tag "logo385x255.png", width: "215" %>
      <br><br><br>
      <center>
      <h1><strong>RECIBO</strong></h1>
      </center>

      <h3>Recebi de Stylo Viagens e Turismo LTDA os itens abaixo relacionados:</h3>

      <table >
      	<thead>
      	  <tr>
      	    <th><h4>Controle</h4></th>
      			<th><h4>Tipo</h4></th>
      			<th><h4>Grupo</h4></th>
      			<th><h4>Tamanho</h4></th>
      	  </tr>
      	</thead>
      	<tbody>
          <% @uniform_pieces.each do |uniform_piece| %>
            <tr>
              <td><%= uniform_piece.id %></td>
              <td><%= uniform_piece.uniform_piece_group.name %></td>
              <td><%= uniform_piece.uniform_piece_kind.name %></td>
              <td><%= uniform_piece.uniform_piece_size.name %></td>
            </tr>
          <% end %>
      	</tbody>
      </table>

      <br>

      <h5><b>Obs.1:</b> O prazo m&iacute;nimo para a troca dos uniformes &eacute; de 01 (um) ano, caso n&atilde;o ocorra imprevistos.</h5>

     <br><br><br><br>
      <center>
        __________________________________________________<br>
        <h2><%= @employer.name %></h2>
        <%= Date.current.to_formatted_s(:rfc822) %>
      </center>

      <style>
        #receiptToPrint {
          width: 700px;
        }
        table {
          border: 1px black solid;
          width: 700px;
        }
        thead {
          border: 2px black solid;
          }
        tfoot, tbody tr td {
          border: 1px black solid;
        }
      </style>
    </div>

  </div>
</div>