config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :users
  end

  get 'admin/index'

  resources :employers, :uniform_piece_groups, :uniform_piece_kinds
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  get 'uniform_pieces/to_employer' => 'uniform_pieces#to_employer'
  
  post 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'
  get 'uniform_pieces/return_to_stock' => 'uniform_pieces#return_to_stock'

  resources :uniform_pieces

   root 'home#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :uniform_pieces
  
  before_save { self.name = name.humanize.titleize }
  
  before_save { self.avatar = 'https://c1.staticflickr.com/9/8542/8666789945_0077a6d060.jpg' }
  
  validates :name, :admission, :sex, presence: true
  
end

app/models/uniform_piece.rb
class UniformPiece < ActiveRecord::Base
  belongs_to :uniform_piece_kind
  belongs_to :uniform_piece_group
  belongs_to :uniform_piece_size
  belongs_to :employer

  attr_accessor :amount

  validates :amount, :entry, :uniform_piece_kind, :uniform_piece_group, :uniform_piece_size, :gender, :color, presence: true
end

app/models/uniform_piece_group.rb
class UniformPieceGroup < ActiveRecord::Base
  validates :name, presence: true
end

app/models/uniform_piece_kind.rb
class UniformPieceKind < ActiveRecord::Base
  validates :name, presence: true
end

app/models/uniform_piece_size.rb
class UniformPieceSize < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :employer
  
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  before_save { self.email = email.downcase }
  validates :employer, :role, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, length: { minimum: 6 }, allow_blank: true, on: :update
  validates :email,    presence: true, format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }

  def admin?
    self.role == 'admin'
  end

  def default?
    self.role == 'default'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_user
  before_action :require_admin

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end
  
  def require_admin
    redirect_to('/', notice: 'Área restrita!') unless current_user.admin?
  end
  
  def is_logged_user?
    redirect_to('/', notice: 'Área restrita!') unless (current_user.id == params[:id].to_i) or current_user.admin?
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :require_user
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.order(:name)
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
    @uniform_pieces = UniformPiece.where(employer_id: nil, gender: [@employer.sex, 'U'])
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Novo funcionário criado com sucesso.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Funcionário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Funcionário excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :avatar, :sex, :admission, :dismiss)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :require_user
  before_action :require_admin, only: [:index, :new, :create, :destroy]
  before_action :is_logged_user?, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :employer_id, :role)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_br(date)
    date.strftime("%d/%m/%Y")
  end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uniform_piece_kinds_helper.rb
module UniformPieceKindsHelper
end

app/helpers/uniform_pieces_helper.rb
module UniformPiecesHelper
  def gender(gender)
    case gender
      when 'M'
        'Masculino'
      when 'F'
        'Feminino'
      when 'U'
        'Unisex'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
Área administrativa

app/views/layouts/_footer.html.erb
<div class="col-md-12">
	<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
	</nav>
</div>

<div class="modal fade" id="modal-container-453150" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">
					Modal title
				</h4>
			</div>
			<div class="modal-body" id="modal-body">
				...
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "IntranetTv", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if controller.controller_name == 'home' %>><%= link_to "Home", root_path %></li>
        <li <%= 'class=active' if controller.controller_name == 'admin' %>><%= link_to "Administração", admin_index_path, class: "disabled" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.employer.name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Meus dados", user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sair", logout_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_menu.html.erb
<div class="row">
  <div class="col-md-12 column">
    <%= link_to "Funcionários", employers_path, class: "btn btn-default btn-block" %>
    <%= link_to "Uniforme", uniform_pieces_path, class: "btn btn-default btn-block" %>
  </div>
</div>

app/views/layouts/_menu_admin.html.erb
<div class="row">
  <div class="col-md-12 column">
    <%= link_to "Usuários", users_path, class: "btn btn-default btn-block" %>
  </div>
</div>

app/views/layouts/_menu_home.html.erb
<div class="row">
  <div class="col-md-12 column">
    <%= link_to "Funcionários", employers_path, class: "btn btn-default btn-block" %>
    <%= link_to "Uniforme", uniform_pieces_path, class: "btn btn-default btn-block" %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntranetTv</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 column">
        <%= render "layouts/menu_admin" %>
      </div>
      <div class="col-md-10 column">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntranetTv</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 column">
        <%= render "layouts/menu" %>
      </div>
      <div class="col-md-10 column">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntranetTv</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-md-offset-4 column">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>